import type { Activity, Project, Task, User } from "@/lib/types";

// Phase 1 mock data. Now superseded by the real MongoDB API (src/services/* + src/store/*),
// but kept as the fallback shape reference and for the seed script's content source.
// Field shapes are identical to the Mongoose models.

export const demoUser: User = {
  id: "user_demo_1",
  name: "Alex Rivera",
  email: "alex@devflow.ai",
  avatar: null,
  bio: "Full-stack developer building delightful products. Coffee-driven.",
  role: "Software Engineer",
  createdAt: "2024-01-12T09:00:00.000Z",
};

export const teamMembers: User[] = [
  demoUser,
  {
    id: "user_demo_2",
    name: "Maya Chen",
    email: "maya@devflow.ai",
    role: "Product Designer",
    createdAt: "2024-02-04T09:00:00.000Z",
  },
  {
    id: "user_demo_3",
    name: "Jordan Park",
    email: "jordan@devflow.ai",
    role: "Backend Engineer",
    createdAt: "2024-02-20T09:00:00.000Z",
  },
  {
    id: "user_demo_4",
    name: "Sam Okafor",
    email: "sam@devflow.ai",
    role: "QA Engineer",
    createdAt: "2024-03-10T09:00:00.000Z",
  },
];

const now = Date.now();
const day = 86_400_000;
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString();

export const projects: Project[] = [
  {
    id: "proj_1",
    name: "DevFlow AI Web App",
    description:
      "Build the core DevFlow AI SaaS dashboard with projects, tasks, kanban and AI task generation.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "active",
    progress: 62,
    members: ["Alex Rivera", "Maya Chen", "Jordan Park"],
    createdAt: iso(-30 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "proj_2",
    name: "Mobile Companion App",
    description:
      "React Native companion for on-the-go task triage and notifications.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "planning",
    progress: 12,
    members: ["Alex Rivera", "Sam Okafor"],
    createdAt: iso(-14 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "proj_3",
    name: "Marketing Website",
    description:
      "Landing page, pricing, blog and docs for the DevFlow AI launch.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "active",
    progress: 38,
    members: ["Maya Chen"],
    createdAt: iso(-21 * day),
    updatedAt: iso(-6 * day),
  },
  {
    id: "proj_4",
    name: "Internal Admin Tools",
    description:
      "Operational dashboards for support, billing analytics and user management.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "completed",
    progress: 100,
    members: ["Jordan Park", "Sam Okafor"],
    createdAt: iso(-90 * day),
    updatedAt: iso(-12 * day),
  },
  {
    id: "proj_5",
    name: "Legacy Migration",
    description:
      "Sunset the v1 monolith and migrate data to the new platform.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "archived",
    progress: 100,
    members: ["Alex Rivera"],
    createdAt: iso(-180 * day),
    updatedAt: iso(-60 * day),
  },
  {
    id: "proj_6",
    name: "Design System v2",
    description:
      "Token-driven theming, accessible components and dark mode polish.",
    owner: "user_demo_1",
    ownerName: "Alex Rivera",
    status: "active",
    progress: 74,
    members: ["Maya Chen", "Alex Rivera"],
    createdAt: iso(-45 * day),
    updatedAt: iso(-3 * day),
  },
];

export const tasks: Task[] = [
  {
    id: "task_1",
    title: "Design dashboard layout",
    description: "Create the dashboard grid, stat cards and chart layout.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "done",
    priority: "high",
    dueDate: iso(-5 * day),
    createdAt: iso(-20 * day),
    updatedAt: iso(-4 * day),
  },
  {
    id: "task_2",
    title: "Implement auth flow",
    description: "Register, login, JWT, protected routes and logout.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_1",
    assignedName: "Alex Rivera",
    status: "in-progress",
    priority: "urgent",
    dueDate: iso(2 * day),
    createdAt: iso(-18 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "task_3",
    title: "Build project CRUD",
    description: "Create, read, update, delete projects with validation.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_3",
    assignedName: "Jordan Park",
    status: "in-progress",
    priority: "high",
    dueDate: iso(4 * day),
    createdAt: iso(-16 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "task_4",
    title: "Kanban drag & drop",
    description: "Implement the kanban board with @dnd-kit and status sync.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_1",
    assignedName: "Alex Rivera",
    status: "todo",
    priority: "medium",
    dueDate: iso(7 * day),
    createdAt: iso(-10 * day),
    updatedAt: iso(-3 * day),
  },
  {
    id: "task_5",
    title: "AI task generation",
    description: "Wire the AI service and the generate-tasks review modal.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_1",
    assignedName: "Alex Rivera",
    status: "todo",
    priority: "high",
    dueDate: iso(10 * day),
    createdAt: iso(-8 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "task_6",
    title: "Analytics charts",
    description: "Recharts for tasks by status/priority and project progress.",
    project: "proj_1",
    projectName: "DevFlow AI Web App",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "done",
    priority: "medium",
    dueDate: iso(-2 * day),
    createdAt: iso(-12 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "task_7",
    title: "Push notifications",
    description: "Realtime notification center and toast system.",
    project: "proj_2",
    projectName: "Mobile Companion App",
    assignedTo: "user_demo_4",
    assignedName: "Sam Okafor",
    status: "todo",
    priority: "low",
    dueDate: iso(14 * day),
    createdAt: iso(-5 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "task_8",
    title: "Offline sync",
    description: "Queue actions offline and reconcile on reconnect.",
    project: "proj_2",
    projectName: "Mobile Companion App",
    assignedTo: "user_demo_3",
    assignedName: "Jordan Park",
    status: "todo",
    priority: "medium",
    dueDate: iso(20 * day),
    createdAt: iso(-4 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "task_9",
    title: "Landing hero section",
    description: "Animated hero with gradient and CTA.",
    project: "proj_3",
    projectName: "Marketing Website",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "in-progress",
    priority: "high",
    dueDate: iso(-1 * day),
    createdAt: iso(-15 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "task_10",
    title: "Pricing page",
    description: "Three-tier pricing table with monthly/yearly toggle.",
    project: "proj_3",
    projectName: "Marketing Website",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "todo",
    priority: "medium",
    dueDate: iso(5 * day),
    createdAt: iso(-7 * day),
    updatedAt: iso(-3 * day),
  },
  {
    id: "task_11",
    title: "Tokenize color palette",
    description: "Move all colors to OKLCH tokens with dark mode variants.",
    project: "proj_6",
    projectName: "Design System v2",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "done",
    priority: "medium",
    dueDate: iso(-3 * day),
    createdAt: iso(-30 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "task_12",
    title: "Accessibility audit",
    description: "WCAG AA pass on all interactive components.",
    project: "proj_6",
    projectName: "Design System v2",
    assignedTo: "user_demo_4",
    assignedName: "Sam Okafor",
    status: "in-progress",
    priority: "high",
    dueDate: iso(3 * day),
    createdAt: iso(-9 * day),
    updatedAt: iso(-1 * day),
  },
  {
    id: "task_13",
    title: "Component docs",
    description: "Document props, variants and usage examples.",
    project: "proj_6",
    projectName: "Design System v2",
    assignedTo: "user_demo_2",
    assignedName: "Maya Chen",
    status: "todo",
    priority: "low",
    dueDate: iso(12 * day),
    createdAt: iso(-6 * day),
    updatedAt: iso(-2 * day),
  },
  {
    id: "task_14",
    title: "Billing analytics view",
    description: "MRR, churn and revenue charts for the admin panel.",
    project: "proj_4",
    projectName: "Internal Admin Tools",
    assignedTo: "user_demo_3",
    assignedName: "Jordan Park",
    status: "done",
    priority: "high",
    dueDate: iso(-20 * day),
    createdAt: iso(-40 * day),
    updatedAt: iso(-15 * day),
  },
];

export const activities: Activity[] = [
  {
    id: "act_1",
    user: "user_demo_1",
    userName: "Alex Rivera",
    action: "completed",
    entityType: "task",
    entityId: "task_6",
    description: "completed task “Analytics charts” in DevFlow AI Web App",
    createdAt: iso(-2 * 3_600_000),
  },
  {
    id: "act_2",
    user: "user_demo_3",
    userName: "Jordan Park",
    action: "updated",
    entityType: "task",
    entityId: "task_3",
    description: "moved “Build project CRUD” to In Progress",
    createdAt: iso(-5 * 3_600_000),
  },
  {
    id: "act_3",
    user: "user_demo_1",
    userName: "Alex Rivera",
    action: "created",
    entityType: "project",
    entityId: "proj_6",
    description: "created project “Design System v2”",
    createdAt: iso(-26 * 3_600_000),
  },
  {
    id: "act_4",
    user: "user_demo_2",
    userName: "Maya Chen",
    action: "updated",
    entityType: "project",
    entityId: "proj_3",
    description: "updated progress on “Marketing Website” to 38%",
    createdAt: iso(-30 * 3_600_000),
  },
  {
    id: "act_5",
    user: "user_demo_4",
    userName: "Sam Okafor",
    action: "created",
    entityType: "task",
    entityId: "task_7",
    description: "created task “Push notifications”",
    createdAt: iso(-48 * 3_600_000),
  },
  {
    id: "act_6",
    user: "user_demo_1",
    userName: "Alex Rivera",
    action: "generated",
    entityType: "ai",
    entityId: "ai_1",
    description: "generated 9 tasks with AI for “Build an e-commerce website”",
    createdAt: iso(-50 * 3_600_000),
  },
  {
    id: "act_7",
    user: "user_demo_3",
    userName: "Jordan Park",
    action: "completed",
    entityType: "project",
    entityId: "proj_4",
    description: "marked project “Internal Admin Tools” as completed",
    createdAt: iso(-70 * 3_600_000),
  },
];
